services:
  wildlifetracker:
    image: wildlifetracker:latest
    build:
      context: .
      dockerfile: WildlifeTracker/Dockerfile
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=WildlifeTracker;User Id=sa;Password=Test123!;TrustServerCertificate=True;
  wildlifetracker.client:
    image: wildlifetracker.client:latest
    build:
      context: ./wildlifetracker.client
      dockerfile: DockerFile
    ports:
      - "4200:80"
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Test123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
volumes:
  sql_data:
