FROM node:22-alpine

WORKDIR usr/src
COPY . .

RUN npm install

RUN npm run build 

FROM nginx:alpine
COPY --from=0 /usr/src/dist/wildlifetracker.client/browser /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
